services:
  emoncms:
    restart: unless-stopped
    image: alexjunk/emoncms
    ports:
      - 7443:443
      - 8081:80
      - 9883:1883
    environment:
      - TZ=Europe/Paris
      - REDIS_BUFFER=1
      - EMONCMS_LOG_LEVEL=2
      - MYSQL_DATABASE=emoncms
      - MQTT_HOST=localhost
      - MQTT_BASETOPIC=emon
      - MQTT_CLIENT_ID=emoncms
      - MQTT_LOG_LEVEL=error
      - CRT_FILE=/etc/ssl/apache2/server.pem
      - KEY_FILE=/etc/ssl/apache2/server.key
      - CNAME=localhost
      - CUSTOM_APACHE_CONF=0
      - USE_HOSTNAME_FOR_MQTT_TOPIC_CLIENTID=0
    env_file:
      - ./.env
    volumes:
      - volume_emoncms:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-file: "5" # number of files or file count
        max-size: "10m" # file size

  httpd:
    image: httpd:latest
    restart: unless-stopped
    ports:
      - 3002:80
    volumes:
      - ./static_web_page:/usr/local/apache2/htdocs
      # - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    logging:
      driver: "json-file"
      options:
        max-file: "5" # number of files or file count
        max-size: "10m" # file size

volumes:
  volume_emoncms:
    driver: local
